### PR TITLE
Add update poa relationship

### PR DESCRIPTION
**Pull request by charleystran**
Adding a service for the update POA relationship endpoint from manage representative service

### CODE REVIEW

**Comment by pkarman** [comment]
@chandracarney thoughts on whether this PR should stay open?

**Comment by charleystran** [comment]
@pkarman I think we can close both of the PR's we have open here on this repo. We ended up making our own fork of the gem.

**Comment by pkarman** [comment]
@charleystran I understand forks are sometimes necessary for dependency maintenance. Still I wonder if there is convergence possible? Caseflow continues to improve this version and it would be a shame if we're duplicating efforts.

**Comment by charleystran** [comment]
@pkarman We decided this for a few reasons. 
1. BGS considers us an external consumer so we need to pass headers Caseflow does not. 
2. We need to be able to merge and approve our changes. Given the couple PR's we had did not have any activity in several months, we decided we need to have our own control of the code we are using.

If we had write access that would be a start but the politics of getting that done would have been a process we didnt have the time for. Ideally there would only be 1 codebase that we could all share, but am not 100% that would work in a practical sense. @bastosmichael I would love to have your take as well

**Pull request closed without merging**
