### PR TITLE
Nemo/Removed Gemfile.lock

### PR DESCRIPTION
**Pull request by nemodjuric**
Connects to #40 

This PR tackled few issues:

- Imposed limitations by Gemfile.lock for any gem that uses it

- There was a conflict with rubocop 0.36 version and rake ~> 11.0 (last_comment method deprecation). 

- ruby-bgs gem fails rubocop validation for the newest rubocop version.

Action: 

-  Removed Gemfile.lock

- Removed rubocop version

- Fixed linting issues found by latest version of rubocop

- Created an issue in Certification to update ruby-bgs file revision.

### CODE REVIEW

**Comment by amprokop** [comment]
Hmmm. Did you mean to remove the Gemfile.lock? It looks like it's still here.

**Comment by amprokop** [comment]
Also, how did you test that this works? This gem unfortunately has no automated tests.

**Comment by nemodjuric** [comment]
bundle exec rake 
rubocop
Both of these should work.

**Comment by nemodjuric** [comment]
Gemfile.lock got re-added while testing, it should be removed now.

**Comment by amprokop** [comment]
@nemodjuric — LGTM. Next, we need to update this in Caseflow. Before we merge the change to the Caseflow gemfile, we should run a sanity check to ensure that BGS calls still work with this version of the gem. Cool?

**Comment by nemodjuric** [comment]
@amprokop I created an issue for updating Caseflow already (see above). I'll look into the best way to test this in Caseflow.

**Pull request merged**
